version: '3.9'

services:
  web:
    build: .
    command: gunicorn drf_project.wsgi:application --bind 0.0.0.0:9000 --workers 4
    # command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/code
    ports:
      - "9000:9000"